version: "3.9"
services:
  # mongodb services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always

  # node services
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      MONGO_PASSWORD: Qwerty123
      PORT: 3000
      JWT_KEY: "secret"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
